import {StyleSheet} from 'react-native';
import Colors from '../../constants/colors';
const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
  },
  btnfield: {
    position: 'absolute',
    width: 330,
    height: 59,
    left: 26,
    top: 650,
    backgroundColor: '#3E54AC',
    borderRadius: 8,
  },
  dbtnfield: {
    position: 'absolute',
    width: 330,
    height: 59,
    left: 26,
    top: 370,
    backgroundColor: '#3E54AC',
    borderRadius: 8,
    elevation: 10,
  },
  btntext: {
    position: 'absolute',
    left: 120,
    top: 15,
    height: 29,
    width: 104,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: 'white',
  },
  dheader: {
    marginTop: -30,
    top: 90,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    zIndex: 1,
    marginLeft: 15,
  },
  detailsContainer: {
    height: '100%',
    width: '100%',

    paddingHorizontal: 20,
    backgroundColor: Colors.main,
    flex: 20,
  },
  iconContainer: {
    height: 60,
    width: 60,
    position: 'absolute',
    top: -30,
    backgroundColor: 'white',
    borderRadius: 30,
    right: 20,
    elevation: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headTxt: {
    width: 276,
    top: 265,
    left: 95,
    fontSize: 64,
    fontFamily: 'Poppins',
    fontWeight: 'bold',
    color: '#3E54AC',
  },
  headphoto: {
    position: 'absolute',
    width: 186,
    height: 173,
    left: 95,
    top: 288,
  },
  headingtext: {
    marginTop:30,
    fontSize: 20,

    fontFamily: 'Poppins-SemiBold',
    color: Colors.white,
  },
  image: {
    flex: 0.7,
    justifyContent: 'center',
  },
  startext: {
    marginTop: -100,
    color: Colors.white,
    fontFamily: 'Poppins-Bold',

    marginLeft: 10,

    zIndex: 1,
    fontSize: 35,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 5,
  },
  title: {
    fontFamily: '800',
    fontSize: 28,
    marginBottom: 10,
    color: '#493d8a',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  detailsdescription: {
    marginTop: 10,
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    color: Colors.buttonColor,
  },
  sizelabel: {
    width: 200,
    height: 48.66,
    left: 20,
    top: 480,
  },
  sizebutton: {
    width: 60,
    height: 40,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(62, 84, 172, 0.65)',
    borderRadius: 3,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizebuttontext: {
    textAlign: 'center',
  },
  description: {
    fontWeight: '300',
    color: '#62656b',
    textAlign: 'center',
    paddingHorizontal: 64,
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  dateText: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#3E54AC',
  },
  datePicker: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    paddingHorizontal: 9,
  },
  dateInput: {
    fontSize: 16,
  },
  categoriesslidescontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  card: {
    marginTop: 20,
    width: 350,
    height: 100,
    margin: 10,
    marginLeft: 20,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardImage: {
    width: '100%',
    height: '110%',
  },
  cardImagetextView: {
    position: 'absolute',
    top: '90%',
    left: '55%',
    transform: [{translateX: -50}, {translateY: -50}],
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardtext: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'poppins',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    paddingLeft: 45,
    paddingRight: 20,
    marginLeft: 20,
    marginRight: 20,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  searchInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingLeft: 100,
    color: '#3E54AC',
  },
  searchIcon: {
    position: 'absolute',
    top: 12.5,
    left: 35,
    zIndex: 1,
    opacity: 0.5,
  },
  imgBack: {
    height: 500,
    width: 405,
    backgroundColor: 'green',
    marginLeft: -5,
  },
  titleText: {marginTop: 20},
});
export default styles;
