import {StyleSheet} from 'react-native';
import Colors from '../../constants/colors';
const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.main,
    width: '100%',
    height: '100%',
  },
  cardContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.Inputtext,
    borderRadius: 10,
    marginLeft: 10,
    marginBottom: 10,
    height: 150,
    width: '90%',
    elevation: 4,
  },
  MainTitleText: {
    alignItems: 'center',
    fontFamily: 'Poppins-Bold',
    color: Colors.black,
    marginLeft: '42%',
    marginTop: 10,
    fontSize: 24,
  },
  images: {
    width: 64,
    height: 100,
    marginRight: 10,
    resizeMode: 'cover',
    borderRadius: 5,
  },
  cardTextContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '85%',
    marginLeft: 10,
    marginTop: 10,
  },
  name: {
    fontSize: 12,
    color: 'black',
    fontFamily: 'Poppins-SemiBold',
    marginRight: 10,
  },
  subContainer: {
    height: '100%',
    width: '85%',
  },
  backContainer: {
    backgroundColor: Colors.Inputtext,
    height: 40,
    width: 40,
    alignItems: 'center',
    borderRadius: 100,
    justifyContent: 'center',
  },
  Backicon: {
    marginLeft: 10,
  },
  disabled: {
    backgroundColor: Colors.gray,
  },
  productname: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
  },
  textContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addButton: {
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  rentButton: {
    backgroundColor: '#3E54AC',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 80,
    marginTop: 10,
    height: 25,
    justifyContent: 'space-between',
  },
  DateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#D9D9D9',
    width: 72,
    height: 20,
    marginLeft: 10,
    marginBottom: 10,
    justifyContent: 'space-between',
  },
  quantityButton: {
    borderRadius: 100,
    height: 24,
    width: 24,
    backgroundColor: Colors.buttonColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 16,
    color: Colors.white,
    fontWeight: 'bold',
  },
  sizeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 40,
    height: 20,
    marginLeft: 6,
    marginTop: 15,
  },
  sizeButton: {
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  GrandtotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
    marginLeft: 25,
  },
  sizeText: {
    fontSize: 12,
    color: 'black',
    fontFamily: 'Poppins-SemiBold',
    marginHorizontal: 5,
  },
  errorContainer: {
    backgroundColor: '#FDD',
    padding: 10,
    borderRadius: 5,
  },
  errorText: {
    color: '#F00',
    fontWeight: 'bold',
    fontSize: 16,
  },
  container: {
    backgroundColor: '#ECF2FF',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  TextTotal: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: 5,
    color: '#3E54AC',
  },
  TextGrand: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: -20,
    left: 20,
    color: '#3E54AC',
    fontSize: 18,
  },
  RemoveButton: {
    height: 25,
    width: '40%',
    backgroundColor: Colors.buttonColor,
    marginTop: 10,
    borderRadius: 5,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  RemoveContainer: {
    marginTop: 10,
  },
  UpdateButton: {
    height: 20,
    width: 40,
    backgroundColor: 'white',
    marginLeft: 30,
    borderRadius: 3,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  PaymentButton: {
    height: 60,
    width: '90%',
    backgroundColor: Colors.buttonColor,
    marginTop: 10,
    marginLeft: 20,
    borderRadius: 100,
    fontFamily: 'Poppins-Medium',
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  PaymentButtonText: {
    color: 'white',
    fontSize: 16,
    height: 25,
    fontFamily: 'Poppins-Medium',
    justifyContent: 'center',
  },
  RemoveButtonText: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    justifyContent: 'center',
  },
  UpdateButtonText: {
    color: Colors.iconscolor,
    fontSize: 9,
    fontWeight: '900',
    justifyContent: 'center',
  },
  removeAndQuantity: {
    flexDirection: 'row',
    marginLeft: 12,
    width: '70%',
    marginTop: 15,
    justifyContent: 'space-between',
  },
  titleContainer: {
    height: 30,
    width: '100%',
    marginLeft: 17,
    borderRadius: 5,
  },
  titleText: {
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: Colors.black,
    marginLeft: 5,
  },
  CartText: {
    color: Colors.black,
    marginTop: 20,
    fontFamily: 'Poppins-Bold',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
    marginLeft: 140,
  },
  ScrollContainer: {
    height: '66%',
    width: '100%',
    marginTop: 16,
    marginLeft: 10,
  },
  productSizeBox: {
    marginTop: 5,
    borderWidth: 1,
    borderRadius: 5,
    marginLeft: 3,
    backgroundColor: Colors.iconscolor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsdescription: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: 'Poppins-SemiBold',
  },
  cardContaineramount: {
    borderWidth: 1,
    borderColor: '#3E54AC1A',
    backgroundColor: '#3E54AC1A',
    borderRadius: 5,
    padding: 10,
    height: 48,
    width: 355,
    left: 20,
    top: -10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 3,
  },
  imageContainer: {
    width: '30%',
    height: '82%',
    marginTop: 10,
    marginLeft: 10,
  },
  priceText: {
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
    color: Colors.buttonColor,
    marginRight: 50,
  },
  priceTotalText: {
    fontSize: 16,
    width: '100%',
    color: Colors.black,
    marginLeft: 40,
    fontFamily: 'Poppins-Medium',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    left: -47,
  },
  GrandtotalText: {
    color: Colors.black,
    fontFamily: 'Poppins-Medium',
    marginLeft: 5,
    fontSize: 16,
  },
  quantityTxt: {
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.black,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
  DateTxt: {
    alignItems: 'center',
    justifyContent: 'center',
    color: Colors.black,
    fontSize: 9,
    width: 55,
    height: 12,
    marginLeft: 7,
    fontFamily: 'Poppins-Medium',
  },
  button: {
    backgroundColor: '#fff',
    paddingHorizontal: 60,
    paddingVertical: 5,
    borderRadius: 5,
  },
  buttonSize: {
    backgroundColor: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 5,
    marginLeft: 5,
    borderWidth: 1,
    borderRadius: 5,
    top: 29,
    left: -310,
    borderColor: '#3E54AC',
    height: 19,
    width: 19,
  },
  buttonRentTo: {
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    left: -75,
    borderColor: '#3E54AC',
    borderWidth: 1,
    width: 57,
    height: 18,
    marginLeft: 25,
    top: -12,
  },
  buttonRentFrom: {
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    left: -15,
    width: 57,
    borderColor: '#3E54AC',
    borderWidth: 1,
    height: 18,
    marginRight: 25,
    top: -12,
  },
  buttonQuantity: {
    backgroundColor: '#fff',
    paddingHorizontal: 2,
    paddingVertical: 2,
    height: 18,
    width: 18,
    borderRadius: 5,
    borderColor: '#3E54AC',
    borderWidth: 1,
    top: 55,
    left: -190,
  },
  buttonText: {
    fontSize: 9,
    fontWeight: 'bold',
    marginLeft: 5,
    marginRight: 5,
  },
  TextSize: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#3E54AC',
    top: 10,
    left: -289,
  },
  TextSizeTo: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#3E54AC',
    top: -10,
    left: -110,
  },
  TextItemname: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#3E54AC',
    top: -30,
    left: -10,
    width: 70,
    height: 69,
  },
  TextRentfrom: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#3E54AC',
    top: -10,
    left: -75,
    width: 70,
    height: 69,
  },
  buttonTextRentfrom: {
    fontSize: 5,
    fontWeight: 'bold',
    marginLeft: 5,
    marginRight: 5,
    alignContent: 'center',
  },
  buttonTextRentto: {
    fontSize: 5,
    fontWeight: 'bold',
    alignContent: 'center',
    left: 8,
  },
  buttonSizeText: {
    fontSize: 6,
    fontWeight: 'bold',
    top: -1,
  },
  buttonTextIncrement: {
    fontSize: 12,
    fontWeight: 'bold',
    top: -3,
    left: 3,
  },
  buttonTextDecrement: {
    fontSize: 12,
    fontWeight: 'bold',
    top: -3,
    left: 3,
  },

  activeButtonText: {
    color: '#fff',
    backgroundColor: '#3E54AC',
    height: 17,
    width: 17,
    borderRadius: 5,
    top: -5,
    left: -6,
  },
  noAddressContainer1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  titleTextContainer1: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    marginLeft: 60,
  },
  imageS1: {
    width: 300,
    height: 300,
    borderRadius: 130,
    marginLeft: -25,
  },
  textContainer1: {
    alignItems: 'center',
  },
  noAddressText1: {
    fontWeight: '500',
    fontSize: 20,
    marginTop: 20,
    marginBottom: 10,
    color: 'white',
  },
  line21: {
    fontSize: 16,
    color: '#8E8E8E',
  },
  lottiecontainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    backgroundColor: Colors.main,
  },
  lottie: {
    height: 200,
    width: 200,
    alignItems: 'center',
    marginLeft: 5,
    justifyContent: 'center',
  },
  Disabled: {
    backgroundColor: 'grey',
  },
  datepickerStyle: {
    backgroundColor: '#D9D9D9',
    width: 75,
    height: 25,
    borderRadius: 8,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  datepickerTextstyle: {color: Colors.black, fontSize: 10},
});
export default styles;
