/* eslint-disable quotes */
import { StyleSheet } from "react-native";
import Colors from "../../constants/colors";

const styles = StyleSheet.create({
  Fullcontainer: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.main,
  },
  backButtonContainer: {
    height: 40,
    width: 40,
    backgroundColor: Colors.white,
    borderRadius: 100,
    marginTop: 30,
    marginLeft: 20,
  },
  mainContainer: {
    width: "100%",
    borderRadius: 10,
  },
  cardContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 8,
    marginLeft: 23,
    marginTop: 15,
    height: 140,
    width: "90%",
    elevation: 4,
    marginBottom: 10,
  },
  containerCheckbox: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    marginLeft: 30,
  },
  textCheckbox: {
    color: Colors.black,
    fontSize: 12,
    marginRight: 10,
    marginBottom: 20,
    fontFamily: "Poppins-Medium",
    textDecorationLine: "underline",
  },
  backBtn: {
    marginTop: 10,
    marginLeft: 5,
    justifyContent: "center",
    alignItems: "center",
    color: "black",
  },
  addressText: {
    color: Colors.black,
    fontSize: 16,
    marginTop: 5,
    fontFamily: "Poppins-SemiBold",
  },
  addressButton: {
    height: 35,
    marginLeft: 20,
    width: 120,
    borderRadius: 4,
  },
  imageContainer: {
    width: "30%",
    height: "90%",
    marginTop: 5,
    marginLeft: 5,
  },
  checkboxContainer: {
    borderColor: "black",
    marginLeft: 0,
    margin: 0,
    padding: 0,
    backgroundColor: "white ",
    borderWidth: 0,
    marginBottom: 20,
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 5,
  },
  cardTextContainer: {
    width: "60%",
  },
  productContainer: {
    flexDirection: "row",
    width: "100%",
    marginTop: 20,
    marginLeft: 10,
    justifyContent: "space-between",
  },
  name: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: "Poppins-Medium",
    marginRight: 25,
  },
  productname: {
    fontSize: 14,
    color: Colors.black,
    fontFamily: "Poppins-SemiBold",
  },
  textContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addButton: {
    backgroundColor: "#fff",
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: "#3E54AC",
  },
  editButton: {
    backgroundColor: "#fff",
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: "#3E54AC",
  },
  addresscard: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    marginLeft: 20,
    marginTop: 20,
    alignItems: "center",
  },
  addresschangeText: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    color: Colors.buttonColor,
    marginTop: 7,
    marginLeft: 10,
    alignItems: "center",
  },
  rentButton: {
    backgroundColor: "#3E54AC",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  SizeandDate: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 10,
  },
  DateContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 5,
    marginLeft: 8,
    width: "40%",
    height: 20,
    marginTop: 10,
    marginBottom: 10,
    justifyContent: "space-between",
    backgroundColor: Colors.white,
  },
  quantityButton: {
    borderRadius: 5,
  },
  quantityText: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: "Poppins-Medium",
  },
  sizeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "95%",
    marginTop: 10,
    marginLeft: 8,
  },
  sizeButton: {
    backgroundColor: "#fff",
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: "#3E54AC",
  },
  sizeText: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: "Poppins-Medium",
  },
  errorContainer: {
    backgroundColor: "#FDD",
    padding: 10,
    borderRadius: 5,
  },
  errorText: {
    color: "#F00",
    fontWeight: "bold",
    fontSize: 16,
  },
  container: {
    backgroundColor: "#ECF2FF",
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  TextTotal: {
    fontWeight: "semibold",
    height: 29,
    width: 130,
    top: 5,
    color: "#3E54AC",
  },
  TextGrand: {
    height: 29,
    width: "100%",
    color: "black",
    fontSize: 16,
    marginTop: 10,
    fontFamily: "Poppins-SemiBold",
    marginLeft: 20,
  },
  RemoveButton: {
    height: 20,
    width: 40,
    backgroundColor: "#3E54AC",
    borderRadius: 3,
    color: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  UpdateButton: {
    height: 20,
    width: 40,
    backgroundColor: "white",
    marginLeft: 30,
    borderRadius: 3,
    color: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  PaymentButton: {
    flexDirection: "row",
    height: 60,
    width: "90%",
    backgroundColor: Colors.buttonColor,
    marginTop: 5,
    borderRadius: 100,
    marginBottom: 20,
    justifyContent: "space-between",
    alignItems: "center",
  },
  PaymentButtonText: {
    color: "white",
    fontSize: 16,
    marginRight: 20,
    fontFamily: "Poppins-Medium",
  },
  RemoveButtonText: {
    color: "white",
    fontSize: 9,
    fontWeight: "500",
    justifyContent: "center",
  },
  UpdateButtonText: {
    color: Colors.iconscolor,
    fontSize: 9,
    fontWeight: "900",
    justifyContent: "center",
  },
  titleContainer: {
    width: "100%",
    marginLeft: 20,
    marginTop: 18,
    borderRadius: 5,
  },
  titleText: {
    fontSize: 24,
    color: Colors.black,
    fontFamily: "Poppins-Bold",
  },
  productSizeBox: {
    marginTop: 5,
    borderWidth: 1,
    borderRadius: 5,
    marginLeft: 3,
    borderColor: "#3E54AC",
    backgroundColor: Colors.iconscolor,
    width: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  detailsdescription: {
    fontSize: 8,
    color: Colors.white,
    fontWeight: "bold",
  },
  cardContaineramount: {
    borderWidth: 1,
    borderColor: "#3E54AC1A",
    backgroundColor: "#3E54AC1A",
    borderRadius: 5,
    padding: 10,
    height: 48,
    width: 355,
    left: 20,
    top: -10,
    flexDirection: "row",
    alignItems: "center",
  },
  priceText: {
    fontSize: 12,
    fontFamily: "Poppins-SemiBold",
    color: Colors.buttonColor,
    marginLeft: 26,
  },
  buttonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    left: -47,
  },
  input: { marginLeft: 15, color: Colors.iconscolor, fontWeight: "500" },
  stateName: {
    marginLeft: 15,
    marginBottom: 10,
    color: Colors.iconscolor,
    fontWeight: "500",
  },
  addressContainer: {
    width: "100%",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  city: {
    marginLeft: 15,
    width: 130,
    height: 70,
    color: Colors.black,
    fontSize: 12,
    fontFamily: "Poppins-Regular",
  },
  addAddressHeader: { flexDirection: "row" },
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    width: "90%",
    height: 120,
    borderColor: "#8E8E8E",
    alignSelf: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    borderRadius: 10,
    elevation: 4,
  },
  quantityTxt: {
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontSize: 10,
    marginLeft: 10,
  },
  DateTxt: {
    alignItems: "center",
    justifyContent: "center",
    color: Colors.black,
    width: "86%",
    height: 12,
    fontSize: 9,
    marginLeft: 4,
    fontFamily: "Poppins-Medium",
  },
  button: {
    backgroundColor: "#fff",
    paddingHorizontal: 60,
    paddingVertical: 5,
    borderRadius: 5,
  },
  buttonSize: {
    backgroundColor: "#fff",
    paddingHorizontal: 6,
    paddingVertical: 5,
    marginLeft: 5,
    borderWidth: 1,
    borderRadius: 5,
    top: 29,
    left: -310,
    borderColor: "#3E54AC",
    height: 19,
    width: 19,
  },
  GrandtotalContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "85%",
    marginLeft: 25,
    marginTop: 20,
  },
  shippingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "85%",
    marginLeft: 25,
  },
  priceTotalText: {
    fontSize: 16,
    color: Colors.black,
    fontFamily: "Poppins-Medium",
  },
  priceTotal: {
    fontSize: 16,
    marginLeft: 10,
    color: Colors.white,
    fontFamily: "Poppins-Medium",
  },
  GrandtotalText: {
    color: Colors.black,
    fontFamily: "Poppins-Medium",
    marginLeft: 5,
    fontSize: 16,
  },
  buttonRentTo: {
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    left: -75,
    borderColor: "#3E54AC",
    borderWidth: 1,
    width: 57,
    height: 18,
    marginLeft: 25,
    top: -12,
  },
  buttonRentFrom: {
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    left: -15,
    width: 57,
    borderColor: "#3E54AC",
    borderWidth: 1,
    height: 18,
    marginRight: 25,
    top: -12,
  },
  buttonTextRentto: {
    fontSize: 5,
    fontWeight: "bold",
    alignContent: "center",
    left: 8,
  },
  buttonSizeText: {
    fontSize: 6,
    fontWeight: "bold",
    top: -1,
  },
  buttonTextIncrement: {
    fontSize: 12,
    fontWeight: "bold",
    top: -3,
    left: 3,
  },
  buttonTextDecrement: {
    fontSize: 12,
    fontWeight: "bold",
    top: -3,
    left: 3,
  },

  activeButtonText: {
    color: "#fff",
    backgroundColor: "#3E54AC",
    height: 17,
    width: 17,
    borderRadius: 5,
    top: -5,
    left: -6,
  },
  checkoutcontainer: {
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    backgroundColor: Colors.main,
  },
  checkoutimage: {
    height: 200,
    width: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  addresstext: {
    width: 60,
    marginLeft: 10,
    height: 20,
    marginTop: 20,
    color: Colors.black,
    fontSize: 12,
    fontFamily: "Poppins-Regular",
  },
  PlaceOrder: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    width: 320,
    backgroundColor: "#3E54AC1A",
    height: 50,
    borderRadius: 5,
    alignItems: "center",
    padding: 10,
  },
});
export default styles;
