export const signupUrl = 'user/signup';
export const wishListRemoveUrl = '/wishlist/remove?productId=';
export const categoryDataUrl = '/category/list';
export const cartRemoveUrl = '/cart/delete/';
export const cartupdateUrl = '/cart/updateQuantity';
export const listAddressUrl = '/address/listAddress';
export const profileDataUrl = '/user/getUser';
export const cartaddUrl = '/cart/add';
export const productaddUrl = '/product/add';
