import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.main,
    paddingVertical: 30,
  },
  failcontainer: {
    width: '100%',
    height: '100%',
    flex: 1,
    backgroundColor: Colors.main,
    paddingVertical: 30,
    flexDirection: 'row',
  },
  headerText: {
    color: Colors.black,
    // fontWeight: 'bold',
    fontFamily: 'Poppins-SemiBold',
    left: 45,
    top: 15,
    fontSize: 16,
  },
  failheaderText: {
    color: Colors.black,
    // fontWeight: 'bold',
    fontFamily: 'Poppins-SemiBold',
    left: 45,
    // top: 15,
    fontSize: 16,
  },
  btnfield: {
    alignItems: 'center',
    width: 300,
    height: 59,
    marginTop: 80,
    // marginLeft: 10,
    backgroundColor: Colors.buttonColor,
    borderRadius: 50,
  },
  btntext: {
    // position: 'absolute',
    left: 165,
    top: 15,
    height: 29,
    width: 304,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: 'white',
  },
  obtnfield: {
    alignItems: 'center',
    width: 300,
    height: 59,
    marginTop: 40,
    // marginLeft: 10,
    backgroundColor: 'white',
    borderRadius: 50,
  },
  obtntext: {
    // position: 'absolute',
    left: 148,
    top: 15,
    height: 29,
    width: 204,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: Colors.buttonColor,
  },
  successText: {
    color: Colors.black,
    textAlign: 'center',
    marginRight: '35%',
    top: 20,
    // fontWeight: 'bold',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
  },
  successText2: {
    color: Colors.black,
    textAlign: 'center',
    // marginRight: '20%',
    top: 20,
    // fontWeight: 'bold',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
  },
  successText1: {
    color: Colors.black,
    textAlign: 'center',
    marginRight: '30%',
    width: '100%',
    top: 30,
    // fontWeight: '400',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
  },
  successText3: {
    color: Colors.black,
    textAlign: 'center',
    // marginRight: '30%',
    width: '100%',
    top: 30,
    // fontWeight: '400',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
  },
  successContainer: {
    alignItems: 'center',
    top: 210,
    width: '100%',
    height: '100%',
    // marginRight: 10,
  },
});
export default styles;
