import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const style = StyleSheet.create({
  container: {
    // backgroundColor: '#000000',
    backgroundColor: Colors.main,
    width: '100%',
    height: 800,
  },
  cardStyle: {
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
    paddingTop: 10,
    shadowColor: 'black',
    borderRadius: 20,
    shadowOffset: {
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  ScardStyle: {
    height: '100%',
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#3E54AC9B',
    shadowColor: 'black',
    borderRadius: 50,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  text: {
    marginLeft: 38,
    // color: '#FFFFFF',
    color: Colors.black,
    fontSize: 16,
    fontFamily: 'poppins',
    marginBottom: -10,
    fontWeight: '700',
  },
  input: {
    textAlign: 'left',
    paddingLeft: 25,
    // backgroundColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: Colors.white,
    marginTop: 25,
    marginBottom: 20,
    height: 56,
    margin: 40,
    fontSize: 18,
    color: Colors.white,
    fontFamily: 'Poppins',
    fontWeight: '700',
    borderRadius: 8,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  emailinput: {
    textAlign: 'left',
    paddingLeft: 20,
    // backgroundColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: Colors.white,
    marginTop: 25,
    marginBottom: 20,
    margin: 40,
    // textAlign: 'center',
    fontSize: 18,
    // color: 'rgba(255, 255, 255, 0.2)',
    color: 'rgba(5, 5, 5, 0.5)',
    fontWeight: '500',
    borderRadius: 10,
    shadowOffset: {},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnfield: {
    alignItems: 'center',
    width: '85%',
    height: 59,
    backgroundColor: '#9747FF',
    borderRadius: 100,
    marginLeft: 28,
    top: 40,
  },
  btnfield1: {
    alignItems: 'center',
    width: 160,
    height: 59,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    top: 40,
  },
  btntext: {
    // position: 'absolute',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    marginLeft: 5,
    fontSize: 20,
    color: 'white',
  },
  btntext1: {
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    top: 14,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: '#3E54AC',
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 60,
    marginLeft: 20,
    marginRight: 20,
  },
  whiteBtn: {
    alignItems: 'center',
    textAlign: 'center',
    width: 300,
    height: 59,
    backgroundColor: 'white',
    borderRadius: 8,
    marginBottom: 15,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnPText: {
    position: 'absolute',
    left: 120,
    top: 15,
    height: 29,
    width: 104,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: '#3E54AC',
  },
  radioChecked: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'black',
    backgroundColor: 'black',
  },
  radioUnchecked: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'black',
  },
  radioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginHorizontal: 45,
  },
  containerRadio: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 10,
    marginBottom: 10,
  },
  radioButtonText: {
    marginLeft: 8,
    marginRight: 30,
    color: 'blue',
    fontSize: 18,
    fontFamily: 'poppins',
    fontWeight: '900',
  },
  radioText2: {
    marginLeft: 8,
    color: 'blue',
    fontSize: 18,
    fontFamily: 'poppins',
    fontWeight: '900',
  },
  addAddressHeader: {
    flexDirection: 'row',
  },
  backBtn: {
    marginTop: 10,
    marginLeft: 25,
    color: 'black',
    // backgroundColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: Colors.black,
    borderRadius: 100,
    width: '9%',
    height: 35,
    flexDirection: 'row',
  },
  btnImage: {width: 24, height: 24, marginTop: 15},
  addAddressText1: {
    marginBottom: 20,
    marginTop: 15,
    marginLeft: 25,
    fontSize: 24,
    color: Colors.black,
    fontWeight: 'bold',
  },
});
export default style;
