import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.main,
    // alignItems: 'center',
    width: '100%',
    height: '100%',
    // padding: 7,
    borderRadius: 10,
  },
  backButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 5,
    marginLeft: 10,
    marginBottom: 10,
    height: 100,
    width: '96%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 4,
  },
  arrowIcon: {
    marginLeft: '90%',
    // marginTop: 20,
  },
  modalContainer: {
    // flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 5,
    marginLeft: '5%',
    marginBottom: 10,
    marginTop: 20,
    height: '70%',
    width: '91%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    // elevation: 4,
  },
  closeButton: {
    backgroundColor: Colors.buttonColor,
    width: '20%',
    borderRadius: 13,
    marginTop: 20,
    marginLeft: '75%',
  },
  closeButtonText: {
    color: Colors.white,
    fontFamily: 'Poppins-Bold',
    alignItems: 'center',
    marginLeft: 17,
  },
  cardTextContainer: {
    // flex: 1,
    justifyContent: 'space-between',
    // backgroundColor: Colors.black,
    width: '100%',
    marginRight: 30,
    // marginTop: -30,
    // flexDirection: 'row',
  },
  orderInfoContainer: {
    justifyContent: 'space-between',
    // backgroundColor: Colors.black,
    width: '100%',
    marginLeft: 10,
    // marginRight: 30,
  },
  name: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#3E54AC',
    fontFamily: 'poppins',
    marginTop: 5,
    marginLeft: 2,
  },
  rentedname: {
    fontSize: 7,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'poppins',
    // marginTop: 2,
    // marginLeft: 2,
  },
  productname: {
    fontSize: 14,
    // fontWeight: 'bold',
    color: Colors.buttonColor,
    fontFamily: 'Poppins-SemiBold',
  },
  QuantityText: {
    fontSize: 13,
    // fontWeight: 'bold',
    color: Colors.black,
    fontFamily: 'Poppins-Medium',
  },
  orderText: {
    fontSize: 13,
    // fontWeight: 'bold',
    color: Colors.green,
    fontFamily: 'Poppins-Medium',
  },
  plcedText: {
    fontSize: 12,
    width: '35%',
    height: 20,
    fontFamily: 'Poppins-Bold',
    // backgroundColor: 'white',
  },
  orderDate: {
    fontSize: 12,
    width: '25%',
    height: 20,
    // marginTop: -30,
    // marginBottom: 50,
    // fontWeight: 'bold',
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    // justifyContent: 'space-between',
    // alignSelf: 'flex-end',
  },
  orderid: {
    fontSize: 15,
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    marginRight: '60%',
  },
  totalOrderText: {
    fontSize: 15,
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    marginRight: '60%',
    width: '50%',
  },
  ordername: {
    fontSize: 12,
    color: Colors.white,
    fontFamily: 'Poppins-Bold',
  },
  productName: {
    fontSize: 14,
    color: Colors.black,
    fontFamily: 'Poppins-Bold',
    // marginLeft: 10,
    marginTop: 10,
  },
  textContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addButton: {
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  rentButton: {
    backgroundColor: '#3E54AC',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3E54AC',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    // marginBottom: 10,
    backgroundColor: '#3E54AC',
    width: 40,
    height: 25,
    justifyContent: 'space-between',
  },
  DateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3E54AC',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    // marginBottom: 10,
    // backgroundColor: 'green',
    width: 80,
    height: 20,
    marginTop: 10,
    marginBottom: 10,
    justifyContent: 'space-between',
  },
  quantityButton: {
    // backgroundColor: '#3E54AC',
    borderRadius: 5,
    // padding: 5,
    // marginHorizontal: 5,
  },
  quantityText: {
    fontSize: 16,
    color: '#3E54AC',
    fontWeight: 'bold',
    // marginHorizontal: 5,
  },
  sizeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3E54AC',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    // marginTop: 10,
  },
  sizeButton: {
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  sizeText: {
    fontSize: 16,
    color: '#3E54AC',
    fontWeight: 'bold',
    marginHorizontal: 5,
  },
  errorContainer: {
    backgroundColor: '#FDD',
    padding: 10,
    borderRadius: 5,
    // marginTop: 10,
  },
  errorText: {
    color: '#F00',
    fontWeight: 'bold',
    fontSize: 16,
  },
  container: {
    // flex: 1,
    height: '100%',
    backgroundColor: '#ECF2FF',
    paddingHorizontal: 20,
    // paddingVertical: 30,
  },
  scrollContainer: {
    height: '100%',
  },
  TextTotal: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: 5,
    color: '#3E54AC',
  },
  TextGrand: {
    fontWeight: 'semibold',
    height: 29,
    width: 130,
    top: -20,
    left: 20,
    color: '#3E54AC',
    fontSize: 18,
  },
  RemoveButton: {
    height: 20,
    width: 40,
    backgroundColor: '#3E54AC',
    // margin: 15,
    // marginTop: 5,
    // marginLeft: 25,
    borderRadius: 3,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  UpdateButton: {
    height: 20,
    width: 40,
    backgroundColor: 'white',
    // margin: 15,
    // marginTop: 5,
    marginLeft: 30,
    borderRadius: 3,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
export default styles;